### ISSUE TITLE
Mass storage images should not be mounted on the Pi

### ISSUE THREAD

**Issue by RoganDawes** [girst/hardpass-passwordmanager#1]
Hi,

I just wanted to point out that the init_usb.sh script incorrectly mounts the hardpass image file prior to exporting it as a mass storage device.

Any changes made to the file by the USB host may not be seen by the Pi, and any changes made by the Pi may not be seen by the host, due to caching effects. Both devices are under the impression that they are in full control of the file system, and simultaneous changes are very likely to result in a corrupted filesystem.

**Comment by girst** [comment]
I have not considered that. As indicated at the top of the file, I am
not the author, but I can look into this if it is a concern. 
(I personally haven't even thought about accessing the image from the
Pi's side, so this wasn't on my radar.)

Tobias

**Comment by RoganDawes** [comment]
Sure, no problem. I'm just using this as a way of playing with the HID emulation on the Zero, but noticed that the file was mounted from both sides. It's worth fixing in your app, though, to ensure that the Pi does not mess up the passwords! ;-)
