### ISSUE TITLE
Issues with Rasberry Pi Zero W and Raspbian

### ISSUE THREAD

**Issue by grmpyninja** [girst/hardpass-passwordmanager#2]
Have you tested USB gadgets on the latest Raspbian? Kernel 4.4

I kind of have issues with multiple gadgets. Trying to set up mass storage and HID, but it looks only one at a time works. When two configured only the first one works fine.

**Comment by girst** [comment]
i haven't worked on the software side for some time. (Currently, getting the hardware done is more interesting to me. [check it out](https://hackaday.io/project/9564/gallery#ab0d7c97eab1d829a3a5e392269068ba))

edited to add:    
i think i have worked on kernel 4.4 iirc. i successfully used ethernet, hid and mass storage (for the ethernet configuration script). have you had a look at my [blog post](http://isticktoit.net/?p=1383#more-1383) about `libcomposite`?

**Comment by coldtofu** [comment]
Hi Girst,

I'm following your site as my first raspberry project.  I've got all my files setup but I'm encountering an issue at start up:
`
/usr/bin/myfile: line 33: 489 Segmentation fault    ls /sys/class/udc > UAC
[FAILED] Failed to start /etc/rc.local Compatiblity.
`
Have you encountered this or can you give suggestion on how I can debug?

Many thanks,

Jeff

**Comment by girst** [comment]
that line should read `ls /sys/class/udc > UDC`. iirc, it should work if you remove this line from your script. 

what is causing a segfault i can't tell

**Comment by coldtofu** [comment]
Hi Girst, 
Many thanks for responding.  Yes, that was a typo, but am I correct in assuming this line:
`ls /sys/class/udc > UIDC`
is needed?

I'm following your blog post, and in the /etc/rc.local, I have it execute a bash script each time at startup similar to the one on your blog (the init_usb.sh).  I've double checked the scripts for other typos and I'm on the latest version:
`Linux raspberrypi-zero 4.9.13+ #974 Wed Mar 1 20:04:40 GMT 2017 armv6l GNU/Linux`

Do you have recommendation on where else to check for issues?

Many thanks,

Jeff

**Comment by girst** [comment]
your problem is a segfault caused likely by the libcomposite/configfs kmod. 

after checking with my pi, the line is indeed needed (it enables/disables the whole gadget). 

try the following:
 * downgrade to kernel 4.4.38 (dec 2016) - that's the one i'm using
 * instead of typing out the script, download it onto the pi directly, take the sd card out of the pi and put it there, ...

**Comment by coldtofu** [comment]
Hi Girst, many thanks for your tip - I will give it a try!
Thanks again,
Jeff
