### ISSUE TITLE
Extending keyboard in scancodes.c

### ISSUE THREAD

**Issue by vasindaniil** [girst/hardpass-passwordmanager#3]
Hello, I'm looking over scancodes.c and I can't seem to understand what the hexcodes exactly relate to, is there a reference for the key possibilities able to be sent?

**Comment by girst** [comment]
i have tried to clean up the documentation in the main repo for this tool. please see https://github.com/girst/hardpasss-sendhid - if you can't figure it out (i won't blame you), just open this issue again
