### ISSUE TITLE
Newline after every character

### ISSUE THREAD

**Issue by Jetjames** [girst/hardpass-passwordmanager#4]
"stops typing at: control characters (including newline)"
If I don't need automatic newline, what I do edit?

**Comment by girst** [comment]
i can't figure out what you want exactly. 

https://github.com/girst/hardpass-sendHID is the new repo for the `scan` utility -- please try this one and open an issue there with more information if you've still got problems. ;-)

**Comment by Jetjames** [comment]
Thank You, I already solved!
