### ISSUE TITLE
hey buddy keep up the good work!

### ISSUE THREAD

**Issue by bmatusiak** [girst/hardpass-passwordmanager#5]
hey buddy keep up the good work!

**Comment by girst** [comment]
thanks.

**Comment by bmatusiak** [comment]
do you have plans on this to keep it going?

**Comment by girst** [comment]
not until i can find a non-usb smart card reader ic with pcsc support.

**Comment by bmatusiak** [comment]
well, i dont know how hard your set on using smart cards, but take a look at zymbit as a security module, they have a hat for pi zero
