### ISSUE TITLE
cannot send keystrokes to computer with raspberry behind a hub

### ISSUE THREAD

**Issue by llpamies** [girst/hardpass-passwordmanager#6]
I read your tutorial http://www.isticktoit.net/?p=1383 on how to setup the Raspberry Pi Zero to act as a keyboard.

This worked fine. But I would like to have the Raspberry Pi to act as a "man-in-the-middle", where I connect a keyboard to it, and it transforms my keypresses before forwarding them to my computer. The idea being to emulate a VIM modal typing in hardware. Since the raspberry pi zero only has one USB, if I plug a hub to it, the sending of key strokes to the computer stops working. I think that hubs do not work if the Pi is in OTG (slave) mode.

Is there any workaround for this?

**Comment by girst** [comment]
this will not work. you could emulate a ps/2 keyboard input, but that is 
outside the scope of this project.
